name       : python-cached-property
version    : 1.5.2
release    : 7
source     :
    - https://github.com/pydanny/cached-property/archive/refs/tags/1.5.2.tar.gz : b566d247a65ece61c62d6fefda082cf3ddca46e800576196657d44d9c4cc5cec
license    : BSD-3-Clause
component  : programming.python
summary    : A decorator for caching properties in classes.
description: A decorator for caching properties in classes.
builddeps  :
    - pkgconfig(python3)
    - python-freezegun
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -k 'not test_threads_ttl_expiry'
